version: "3"

services:
  machine:
    container_name: "drug_resistance_prediction"
    build: . 
    volumes:
      - './scripts:/home/scripts:delegated'
      - './data:/home/data:delegated'
      - './bio-softwares:/home/bio-softwares:delegated'
      - './de-novo:/home/de-novo:delegated'
      - './ref-map:/home/ref-map:delegated'
